org: rexben001
app: testing-scheduling
service: aws-node-scheduled-cron-project

frameworkVersion: '2 || 3'


plugins:
  - serverless-offline-scheduler
  - serverless-offline


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    DB_HOST: localhost
    DB_USER: testadmin
    DB_PASS: password
    DB_NAME: readeotest
 

functions:
  rateHandler:
    handler: handler.run
    events:
      - schedule: rate(1 minute)

